name: Fantasy Recap (YGITB + XFL) – Wednesdays AU

on:
  schedule:
    # Sydney 09:00 Wednesday
    # AEST (UTC+10) → Tue 23:00 UTC
    # AEDT (UTC+11) → Tue 22:00 UTC
    - cron: "0 22 * * TUE"
    - cron: "0 23 * * TUE"
  workflow_dispatch: {}

jobs:
  recap:
    runs-on: ubuntu-latest
    concurrency:
      group: reports-${{ github.workflow }}-${{ matrix.name }}
      cancel-in-progress: true

    strategy:
      matrix:
        include:
          - name: ygitb
            league_id: "1260643183704932352"
            outdir: "reports/ygitb"
          - name: xfl
            league_id: "1238082932220891136"
            outdir: "reports/xfl"

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        working-directory: fantasy-bot
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Env sanity check
        working-directory: fantasy-bot
        env:
          SLEEPER_LEAGUE_ID: ${{ matrix.league_id }}
        run: |
          [ -z "${SLEEPER_LEAGUE_ID}" ] && echo "Missing league id" && exit 1 || echo "League ID present."

      - name: Run RECAP (prev week)
        working-directory: fantasy-bot
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          SLEEPER_LEAGUE_ID: ${{ matrix.league_id }}
          TIMEZONE: Australia/Sydney
          OUTPUT_DIR: ${{ matrix.outdir }}
          DISABLE_TIMEGATE: "1"
        run: |
          echo "Recap for ${{ matrix.name }} -> ${{ matrix.outdir }}"
          python -m scripts.run_bot recap

      - name: Commit & push reports (if any changed)
        env:
          BRANCH_NAME: ${{ github.ref_name }}
        run: |
          # Configure author
          git config user.name "${{ secrets.REPO_COMMIT_AUTHOR_NAME || 'Fantasy Bot' }}"
          git config user.email "${{ secrets.REPO_COMMIT_AUTHOR_EMAIL || 'bot@example.com' }}"

          # Only stage report files (avoid __pycache__ etc.)
          git add -A fantasy-bot/reports

          # Exit early if nothing staged
          if git diff --cached --quiet; then
            echo "No report changes to commit."
            exit 0
          fi

          git commit -m "chore(recap): update ${{ matrix.name }} $(date -u +'%Y-%m-%dT%H:%MZ')"

          # Rebase on latest remote before pushing
          git fetch origin
          BRANCH="${BRANCH_NAME:-main}"
          git pull --rebase origin "$BRANCH" || (echo "Rebase failed; aborting" && git rebase --abort && exit 1)

          git push origin HEAD:"$BRANCH"
