name: Sleeper History Weekly

concurrency:
  group: data-updater-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write

on:
  schedule:
    - cron: "0 23 * * 2"   # Wed 9am Sydney
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0   # allow rebase/pull on main

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Run collectors
        run: |
          set -eux
          python -u scripts/sleeper_history.py
          python -u scripts/aggregate_stats.py

      - name: Commit & push data
        run: |
          set -eux
          git config user.name "github-actions"
          git config user.email "actions@github.com"

          # Only commit if there are changes
          if ! git diff --quiet; then
            git add -A
            git commit -m "Update league data [skip ci]" || true

            # Integrate any new remote commits that landed while we were running
            git fetch origin
            git pull --rebase --autostash origin main || true

            # Try a normal push first; if main moved again, use a safe force
            git push origin HEAD:main || git push --force-with-lease origin HEAD:main
          else
            echo "No changes"
          fi
